name: azkari_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^19.3.0
  flutter_native_splash: 2.4.1
  timezone: ^0.10.1

  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.2+1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  sqlite3_flutter_libs: ^0.5.18

flutter:
  uses-material-design: true

  assets:
    - assets/database_files/azkar.db

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
