name: azkari_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.2+1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  sqlite3_flutter_libs: ^0.5.18

flutter:
  uses-material-design: true

  assets:
    - assets/database_files/azkar.db
    - assets/images/
    - assets/screenshots/

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#F5F5F5"
  color_dark: "#121212"
  image: "assets/images/app_logo.png"

  android_12:
    color: "#F5F5F5"
    color_dark: "#121212"
    image: "assets/images/app_logo.png"
